import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { AuthProvider } from "@/context/AuthContext" 

// Import Navbar and Footer
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Kwalas Tech",
  description: "Generated by create next app",
  icons: {
    icon: "/kwala.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${jetbrains.variable}`}>
      <body className="bg-background text-foreground antialiased font-sans">
        <AuthProvider>
          <Navbar />
          <main>{children}</main>
          <Toaster position="top-right" />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
